- lib/util/check-existence.js
- tests/fixtures/no-missing-require/a.config.js
- tests/lib/rules/no-missing-import.js
- tests/lib/rules/no-missing-require.js
Version 0.3.0 throws a spurious error on e.g. `require('./webpack.config')` when `./webpack.config.js` exists. This PR includes a fix and tests.
> allow dots in names of required and imported files

- docs/rules/shebang.md
- lib/rules/shebang.js
- tests/lib/rules/shebang.js
> Update: `shebang` came to check BOM and `\r\n`

- docs/rules/no-unsupported-features.md
- lib/rules/no-unsupported-features.js
- package.json
- tests/fixtures/no-unsupported-features/gte-0.12.8/package.json
- tests/fixtures/no-unsupported-features/gte-4.0.0/package.json
- tests/fixtures/no-unsupported-features/gte-4.4.0-lt-5.0.0/package.json
- tests/fixtures/no-unsupported-features/hat-4.1.2/package.json
- tests/fixtures/no-unsupported-features/invalid/package.json
- tests/fixtures/no-unsupported-features/lt-6.0.0/package.json
- tests/fixtures/no-unsupported-features/nothing/package.json
- tests/lib/rules/no-unsupported-features.js
Fixes #29.
This depends on undocumented APIs of `semver` module. So I pinned the version of `semver`.
> Update: `no-unsupported-features` gets reading `engines` of `package.json` (fixes #29)

- conf/recommended.json
- scripts/generate-index.js
This pull request is one of PoC for #38 .
If this is merged, we can configure .eslintrc using plugin:node/recommended.
like this
```json
{
"extends": [
"plugin:node/recommended"
],
"parserOptions": {
"ecmaVersion": 6
},
"plugins": [
"node"
]
}
```
This configure equals to
```json
{
"parserOptions": {
"ecmaVersion": 6
},
"plugins": [
"node"
],
"env": {
"node": true,
"es6": true
},
"rules": {
"node/no-deprecated-api": "error",
"node/no-missing-import": "error",
"node/no-missing-require": "error",
"node/no-unpublished-import": "error",
"node/no-unpublished-require": "error",
"node/no-unsupported-features": ["error",{"version": 4}],
"node/shebang": "error"
}
}
```
> New: add `plugin:node/recommended` config

- lib/rules/no-deprecated-api.js
- tests/lib/rules/no-deprecated-api.js
When assigning to a standard library module, `no-deprecated-api` stores the name of the variable that was assigned, and track references to it. However, if the variable has no declaration, it was throwing an error (see https://github.com/mysticatea/eslint-plugin-node/issues/55):
```js
foo = require('fs');
```
This fixes the issue by adding a null check to ensure that the variable has a declaration.
> Fix: `no-deprecated-api` crash on undeclared assignment (fixes #55)

- docs/rules/no-deprecated-api.md
- lib/util/deprecated-apis.js
- tests/lib/rules/no-deprecated-api.js
The new Buffer APIs were backported to 4.5.0, so we should update the
error message so users who don't care about <4.5.0 can avoid using
safe-buffer.
The changelog for 4.5.0 is here: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V4.md#2016-08-15-version-450-argon-lts-thealphanerd
> New Buffer APIs are available in 4.5.0

- lib/util/get-npmignore.js
- tests/lib/rules/no-unpublished-import.js
- tests/lib/rules/no-unpublished-require.js
This implements one of the approaches I outlined in issue #73 to ensure that files like `test/readme.js` (has a basename equal to something that npm auto-publishes, but is not in the package root) are not treated as published and so can require devDependencies.
Specifically, when using the NEVER_IGNORED regex, this PR will pass the full relative path from package root to the linted file, instead of the linted file's basename. All existing tests pass with this logic, and my new tests also pass (but failed with the old logic).
Please let me know if I should make any changes.
> Fix: README etc. are only assumed published if in pkg root (fixes #73)

- docs/rules/no-missing-require.md
- lib/util/check-existence.js
- lib/util/get-resolve-paths.js
- tests/lib/rules/no-missing-require.js
Makes it possible to set the `paths` option on `resolve`.
https://www.npmjs.com/package/resolve#resolveid-opts-cb
> Set resolve paths option

- lib/rules/no-unsupported-features.js
- package.json
- tests/lib/rules/no-unsupported-features.js
This patch makes the minimum changes needed to remove all use of undocumented semver API's so it can be unpinned.  This results in a slight change to the error message generated when package.json contains engines.node.  We no longer calculate the lowest supported version so the message now contains the sanitized semver range string insead of a single version.
> no-unsupported-features: Use semver public API's.

- lib/rules/exports-style.js
- lib/rules/no-deprecated-api.js
- lib/rules/no-extraneous-import.js
- lib/rules/no-extraneous-require.js
- lib/rules/no-hide-core-modules.js
- lib/rules/no-missing-import.js
- lib/rules/no-missing-require.js
- lib/rules/no-unpublished-bin.js
- lib/rules/no-unpublished-import.js
- lib/rules/no-unpublished-require.js
- lib/rules/no-unsupported-features.js
- lib/rules/process-exit-as-throw.js
- lib/rules/shebang.js
ESLint v4.15.0 added an official location for rules to store a URL to their documentation in the rule metadata in eslint/eslint#9788. This adds the URL to all the existing rules so anything consuming them can
know where their documentation is without having to resort to external packages to guess.
> Add URL to rule documentation to the metadata

- lib/rules/exports-style.js
- lib/rules/no-deprecated-api.js
- lib/rules/no-extraneous-import.js
- lib/rules/no-extraneous-require.js
- lib/rules/no-hide-core-modules.js
- lib/rules/no-missing-import.js
- lib/rules/no-missing-require.js
- lib/rules/no-unpublished-bin.js
- lib/rules/no-unpublished-import.js
- lib/rules/no-unpublished-require.js
- lib/rules/no-unsupported-features.js
- lib/rules/process-exit-as-throw.js
- lib/rules/shebang.js
- lib/util/get-docs-url.js
This adds a utility function and uses the version present in package.json for generating the URL to tagged version of the rule documentation. I think this is good because the documentation will match the version the user has installed. This way, even if a rule is changed or removed in the future, the user can find the documentation with ease.
_Note: This is very similar to the PR mysticatea/eslint-plugin-eslint-comments#11, but including the same description just to be through._
> Docs: Use link to tagged version for rule docs

- lib/util/deprecated-apis.js
`safe-buffer.Buffer` function/constructor is just a re-export of `buffer.Buffer` and should be deprecated likewise.
Otherwise, using `Buffer = require('safe-buffer').Buffer` magically hides the deprecation message, which it shouldn't, as that code will actually cause runtime deprecation errors on Node.js >= 10.
In fact, ecosystem analysis shows that people do that a lot to silence `standard` linter — they see a recommendation to use `safe-buffer` in the warning, they throw in `var Buffer = require('buffer').Buffer`, the warning goes away, nothing actually changes.
Example:
* https://github.com/webdriverio/webdriverio/commit/05cbd3167c12e4930f09ef7cf93b127ba4effae4#diff-124380949022817b90b622871837d56cR31 (a module with 548 759 downloads/month),
* and there are more of those.
Also, even if …
> Breaking: deprecate safe-buffer.Buffer calls

- README.md
- lib/recommended.json
We do not need to write `plugins: ["node"]` when using recommended configuration.
Inspired by <https://github.com/mysticatea/eslint-plugin-eslint-comments>.
> Chore: shorter recommended configuration

- README.md
no-unsupported-features was replaced by no-unsupported-ecma-features.
I noticed the the rule tables was auto-gened. a better way is to update the build script.
> Docs: add deprecated rules table (fixes #129)

- docs/rules/prefer-global/url-search-params.md
`prefer-global/url-search-params.md` currently references the rule `node/prefer-global/url` rather than `node/prefer-global/url-search-params`.
> Fix url-search-params documentation

- lib/rules/no-deprecated-api.js
- tests/fixtures/no-missing/a.config.js
- tests/fixtures/no-missing/a.js
- tests/fixtures/no-missing/bar/main.js
- tests/fixtures/no-missing/foo/main.js
- tests/fixtures/no-missing/index.js
Fixes #142
Node.js doc: 
- [crypto.createCipher](https://nodejs.org/api/crypto.html#crypto_crypto_createcipher_algorithm_password_options)
- [crypto.createDecipher](https://nodejs.org/api/crypto.html#crypto_crypto_createdecipher_algorithm_password_options)
> Fix: lint replaceBy messages

- azure-pipelines.yml
- lib/rules/process-exit-as-throw.js
- package.json
- tests/lib/rules/no-deprecated-api.js
- tests/lib/rules/no-extraneous-import.js
- tests/lib/rules/no-missing-import.js
- tests/lib/rules/no-unpublished-import.js
- tests/lib/rules/no-unsupported-features/es-builtins.js
- tests/lib/rules/no-unsupported-features/es-syntax.js
This PR fixes some import of internal files and fixes for the breaking changes of ESLint 6.
> fix for ESLint 6

- .azure-pipelines/lint-job.yml
- .azure-pipelines/test-job.yml
- azure-pipelines.yml
- package.json
This PR makes CI Jobs using templates to reduce redundant definitions.
> ⚒ improve azure-pipelines.yml

- lib/rules/no-unsupported-features.js
- lib/rules/no-unsupported-features/es-syntax.js
Just a typo-fix PR. ('nomalizeScope' -> 'normalizeScope')
> Typos in function names has been fixed.

- docs/rules/no-callback-literal.md
- lib/rules/no-callback-literal.js
- tests/lib/rules/no-callback-literal.js
Fixes: https://github.com/mysticatea/eslint-plugin-node/issues/178
> Add no-callback-literal rule

- lib/util/visit-import.js
- tests/lib/rules/no-missing-import.js
> fix dynamic import

- docs/rules/no-deprecated-api.md
These APIs were removed from the rule in https://github.com/mysticatea/eslint-plugin-node/commit/276a9ad0fa8d6db224aae6fe6d35146a3fac9377, however, the documentation was not updated.
> Update no-deprecated-api documentation

- lib/rules/no-unsupported-features/node-builtins.js
- tests/lib/rules/no-unsupported-features/node-builtins.js
- experimental [`assert.CallTracker`](https://nodejs.org/api/assert.html#assert_new_assert_calltracker)
> 💥Update node/no-unsupported-features/node-builtins to recognize new assert features

- lib/rules/no-unsupported-features/node-builtins.js
- tests/lib/rules/no-unsupported-features/node-builtins.js
Update node/no-unsupported-features/node-builtins to recognize new fs methods and classes.
- `fs/promises`
- `fs.lutimes`
- `fs.lutimesSync`
- `fs.rm`
- `fs.rmSync`
- `fs.read`
- `fs.readSync`
- `fs.opendir`
- `fs.opendirSync`
- `fs.readv`
- `fs.readvSync`
- `fs.Dir`
- `fs.StatWatcher`
> 💥Update node/no-unsupported-features/node-builtins to recognize new fs features

- lib/rules/no-unsupported-features/node-builtins.js
- tests/lib/rules/no-unsupported-features/node-builtins.js
Update node/no-unsupported-feature/node-builtins
- [`async_hooks.AsyncLocalStorage`](https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage)
> 💥Update node/no-unsupported-features/node-builtins to recognize new async_hooks features

- lib/rules/no-unsupported-features/node-builtins.js
- tests/lib/rules/no-unsupported-features/node-builtins.js
Add experimental [`buffer.Blob`](https://nodejs.org/api/buffer.html#buffer_class_blob).
> 💥Update node/no-unsupported-features/node-builtins to recognize new buffer features

- lib/rules/no-unsupported-features/es-syntax.js
- package.json
- tests/lib/rules/no-unsupported-features/es-syntax.js
> 💥 update node/no-unsupported-features/es-builtins rule to recognize optional chaining and nullish coalescing operators

- lib/util/visit-import.js
- lib/util/visit-require.js
- package.json
- tests/lib/rules/no-missing-import.js
- tests/lib/rules/no-missing-require.js
As requested in #275, recognize Node.js core modules referenced using the [node:](https://nodejs.org/api/esm.html#esm_node_imports) URL scheme.
Since `resolve.isCore` was moved to `is-core-module` in https://github.com/browserify/resolve/commit/7c26483576f7a44573ddc61cd5d51519deb674c5 and `is-core-module@2.3.0` added support for `node:` in https://github.com/inspect-js/is-core-module/commit/73412230a769f6e81c05eea50b6520cebf54ed2f require `is-core-module@^2.3.0`.
**Note:** `is-core-module` checks whether the module is supported in a given Node.js version (if not provided, the current version is checked).  Although checking whether a name is a core module in all Node.js versions supported by the package would be ideal, it will require significantly more design and implementation work and …
> use is-core-module@^2.3.0 to support node: scheme

- docs/rules/no-unsupported-features/es-syntax.md
This PR adds the new properties to the `node/no-unsupported-features/es-syntax` rule document.
> Add new properties to `no-unsupported-features/es-syntax` rule doc
